/********************* ROLES **********************/

/********************* UDFS ***********************/

/****************** GENERATORS ********************/

CREATE GENERATOR "fileinfo";
CREATE GENERATOR "filter_words";
CREATE GENERATOR "filters";
CREATE GENERATOR "group_words";
CREATE GENERATOR "grp_cncpt";
CREATE GENERATOR "utenti";
/******************** DOMAINS *********************/

/******************* PROCEDURES ******************/

SET TERM ^ ;
CREATE PROCEDURE CLEAR_DB
AS
BEGIN EXIT; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE INSER_ASS_FILE_SIGWORDS (
    GROUPID Integer,
    FILEID Integer,
    SIGWORD Varchar(100) )
RETURNS (
    NRECORD Integer )
AS
BEGIN EXIT; END^
SET TERM ; ^

SET TERM ^ ;
CREATE PROCEDURE UPDATE_SIG_WORD (
    GRP_CNCPT Integer,
    WORD Varchar(100),
    ADDED_RELEVANCE Float,
    WITH_INSERT Char(1) )
RETURNS (
    ADDED_RECORDS Integer,
    UPDATE_DRECORDS Integer )
AS
BEGIN EXIT; END^
SET TERM ; ^

/******************** TABLES **********************/

CREATE TABLE FILEINFO
(
  ID Integer NOT NULL,
  DESCRIZIONE Varchar(250) CHARACTER SET WIN1252 NOT NULL,
  DATA Timestamp NOT NULL,
  VERSIONE Smallint NOT NULL,
  NOMEFILE Varchar(100) CHARACTER SET WIN1252 NOT NULL,
  ESTENSIONE Varchar(12) CHARACTER SET WIN1252 NOT NULL,
  ARCH_PATH Varchar(100) CHARACTER SET WIN1252 NOT NULL,
  LANGUAGE_FILTER Integer NOT NULL,
  ORIG_PATH Varchar(100) CHARACTER SET ASCII,
  OWNER_ID Integer NOT NULL,
  INSERTION_DATE Timestamp NOT NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE FILE_SIG_WORDS
(
  FILE_ID Integer NOT NULL,
  WORD_ID Integer NOT NULL,
  CONSTRAINT UNQ_FILE_SIG_WORDS UNIQUE (FILE_ID,WORD_ID)
);
CREATE TABLE FILTERS_DESCR
(
  ID Integer NOT NULL,
  DESCR Varchar(40) CHARACTER SET WIN1252 NOT NULL,
  "USER" Integer NOT NULL,
  LINGUISTIC Char(1) CHARACTER SET WIN1252,
  PRIMARY KEY (ID),
  CONSTRAINT UNQ_FILTERS_DESCR UNIQUE (DESCR,"USER")
);
CREATE TABLE FILTERS_WORDS
(
  DESCR Integer NOT NULL,
  WORD Varchar(40) CHARACTER SET WIN1252 NOT NULL,
  ID Integer NOT NULL,
  RELEVANCE Float NOT NULL,
  CONSTRAINT PRIMARY_KEY PRIMARY KEY (ID),
  CONSTRAINT UNQ_DESCR_WORDS UNIQUE (DESCR,WORD)
);
CREATE TABLE GRP_CNCPT
(
  ID Integer NOT NULL,
  DESCR Varchar(80) CHARACTER SET WIN1252 NOT NULL,
  "USER" Integer,
  PRIMARY KEY (ID)
);
CREATE TABLE GRP_CNCPT_FILES
(
  GRP_CNCPT Integer NOT NULL,
  "FILE" Integer NOT NULL,
  CONSTRAINT PK_GRP_CNCPT_FILES_KEY PRIMARY KEY (GRP_CNCPT,"FILE")
);
CREATE TABLE GRP_CNCPT_WORDS
(
  GRP_CNCPT Integer NOT NULL,
  WORD Varchar(40) CHARACTER SET WIN1252 NOT NULL,
  ID Integer NOT NULL,
  RELEVANCE Float NOT NULL,
  CONSTRAINT ID PRIMARY KEY (ID),
  CONSTRAINT UNIQUENESS_GRPID_WORD UNIQUE (GRP_CNCPT,WORD)
);
CREATE TABLE LASTPATH
(
  PATH1 Integer NOT NULL,
  PATH2 Integer NOT NULL,
  PATH3 Integer NOT NULL,
  PATH4 Integer NOT NULL
);
CREATE TABLE UTENTI
(
  ID Integer NOT NULL,
  USERNAME Varchar(40) CHARACTER SET WIN1252 NOT NULL,
  IDENTIFIER Varchar(40) CHARACTER SET WIN1252,
  "PASSWORD" Varchar(40) CHARACTER SET WIN1252 NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT UNIQUENESS_USERNAME UNIQUE (IDENTIFIER)
);
/********************* VIEWS **********************/

/******************* EXCEPTIONS *******************/

/******************** TRIGGERS ********************/

SET TERM ^ ;
CREATE TRIGGER NEW_FILTER_WORD FOR FILTERS_WORDS ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID("filter_words",1);
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER NEW_GROUP_WORD FOR GRP_CNCPT_WORDS ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID("group_words",1);
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER UTENTI_ID FOR UTENTI ACTIVE
BEFORE INSERT POSITION 1
AS 
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID("utenti",1);
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER "filtersID" FOR FILTERS_DESCR ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID("filters",1);
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER "grp_cncpt" FOR GRP_CNCPT ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID("grp_cncpt",1);
END^
SET TERM ; ^

SET TERM ^ ;
ALTER PROCEDURE CLEAR_DB
AS
BEGIN
    delete from GRP_CNCPT_FILES;
    delete from FILE_SIG_WORDS;
    delete from GRP_CNCPT;
    delete from GRP_CNCPT_WORDS;
    delete from FILTERS_DESCR;
    delete from FILTERS_WORDS;
    delete from FILEINFO;
    delete from LASTPATH;
    delete from UTENTI;
END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE CLEAR_DB TO  "SYSDBA";


SET TERM ^ ;
ALTER PROCEDURE INSER_ASS_FILE_SIGWORDS (
    GROUPID Integer,
    FILEID Integer,
    SIGWORD Varchar(100) )
RETURNS (
    NRECORD Integer )
AS
DECLARE VARIABLE wordID INTEGER;

BEGIN
    select GCW.ID from GRP_CNCPT_WORDS GCW
    where GCW.GRP_CNCPT = :groupID and GCW.WORD = :sigWord and GCW.ID not in (
        select FSW.WORD_ID from FILE_SIG_WORDS FSW
        where FSW.FILE_ID = :fileID and FSW.WORD_ID = GCW.ID ) into :wordID;

    if(wordID is not NULL) THEN
        BEGIN
        insert into FILE_SIG_WORDS(FILE_ID, WORD_ID)
        values(:fileID, :wordID);
        NRECORD = 1;
        END
    else NRECORD = 0;
END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE INSER_ASS_FILE_SIGWORDS TO  "DMSERVER" WITH GRANT OPTION;

GRANT EXECUTE
 ON PROCEDURE INSER_ASS_FILE_SIGWORDS TO  "SYSDBA";

UPDATE RDB$PROCEDURES set
  RDB$DESCRIPTION = 'Inserisce l''associazione tra un elemento in e una parola (sottintendendo che si tratti di una parola significativa) per un dato gruppo.
Se la parola da associare non e` contenuta nella tabella GRP_CNCPT_WORDS non avviene nessun inserimento.
Se l''associazione esiste gia` non avviene nessun aggiornamento.'
  where RDB$PROCEDURE_NAME = 'INSER_ASS_FILE_SIGWORDS';
UPDATE RDB$PROCEDURE_PARAMETERS set RDB$DESCRIPTION = 'ID del gruppo a cui appartiene l''alemento.'
  where RDB$PARAMETER_NAME = 'GROUPID' AND RDB$PROCEDURE_NAME = 'INSER_ASS_FILE_SIGWORDS';
UPDATE RDB$PROCEDURE_PARAMETERS set RDB$DESCRIPTION = 'ID del file (rappresentato dall''elemento ossia dal record in FILEINFO)  a cui deve essere associata la parola.'
  where RDB$PARAMETER_NAME = 'FILEID' AND RDB$PROCEDURE_NAME = 'INSER_ASS_FILE_SIGWORDS';
UPDATE RDB$PROCEDURE_PARAMETERS set RDB$DESCRIPTION = 'Costituisce l''input principale per il quale e` stata creta pa procedura e rappresenta la parola da associare per il gruppo specificato espressa con la stringa stessa in quanto l''ipotesi e` che non si conosca a priori l''ID della parola stessa.'
  where RDB$PARAMETER_NAME = 'SIGWORD' AND RDB$PROCEDURE_NAME = 'INSER_ASS_FILE_SIGWORDS';

SET TERM ^ ;
ALTER PROCEDURE UPDATE_SIG_WORD (
    GRP_CNCPT Integer,
    WORD Varchar(100),
    ADDED_RELEVANCE Float,
    WITH_INSERT Char(1) )
RETURNS (
    ADDED_RECORDS Integer,
    UPDATE_DRECORDS Integer )
AS
DECLARE VARIABLE ID integer;
    BEGIN
        ID = null;
        ADDED_RECORDS = 0;
        UPDATE_DRECORDS = 0;
        select ID from GRP_CNCPT_WORDS where GRP_CNCPT = :GRP_CNCPT and WORD = :WORD  into :ID;
        IF(ID is not null) THEN
        BEGIN
            update GRP_CNCPT_WORDS  set RELEVANCE = RELEVANCE + :ADDED_RELEVANCE
            where GRP_CNCPT = :GRP_CNCPT and WORD = :WORD;
            UPDATE_DRECORDS = 1;
        END
        else if(WITH_INSERT = '1') then
        BEGIN
            insert into GRP_CNCPT_WORDS(GRP_CNCPT, "WORD", RELEVANCE) values (:GRP_CNCPT, :WORD, :ADDED_RELEVANCE);
            ADDED_RECORDS = 1;
        END
    END^
SET TERM ; ^

GRANT EXECUTE
 ON PROCEDURE UPDATE_SIG_WORD TO  "DMSERVER" WITH GRANT OPTION;

GRANT EXECUTE
 ON PROCEDURE UPDATE_SIG_WORD TO  "SYSDBA";

UPDATE RDB$PROCEDURES set
  RDB$DESCRIPTION = 'Aggiorna il punteggio di una parola associate ad un determinato gruppo (tabella GRP_CNCPT_WORD).
Se la parola non esiste viene creata anche se il punteggio deve essere decrementato (viene quindi impostato ad un valore negativo).'
  where RDB$PROCEDURE_NAME = 'UPDATE_SIG_WORD';

UPDATE RDB$RELATION_FIELDS set RDB$DESCRIPTION = 'Qui viene immessa una breve descrizione oppure il titolo del documento (uso piu` frequente).'  where RDB$FIELD_NAME = 'DESCRIZIONE' and RDB$RELATION_NAME = 'FILEINFO';
ALTER TABLE FILEINFO ADD CONSTRAINT OWNER_ID_USER_ID
  FOREIGN KEY (OWNER_ID) REFERENCES UTENTI (ID) ON UPDATE CASCADE ON DELETE CASCADE;
CREATE INDEX IFILEINFONEWINDEX ON FILEINFO (DESCRIZIONE);
CREATE INDEX INDEXNOMI ON FILEINFO (NOMEFILE);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON FILEINFO TO  "DMSERVER";

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON FILEINFO TO  "SYSDBA" WITH GRANT OPTION;

ALTER TABLE FILE_SIG_WORDS ADD CONSTRAINT FK_FILE_SIG_WORDS
  FOREIGN KEY (FILE_ID) REFERENCES FILEINFO (ID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE FILE_SIG_WORDS ADD CONSTRAINT FK_WORD_SIG_WORDS
  FOREIGN KEY (WORD_ID) REFERENCES GRP_CNCPT_WORDS (ID) ON UPDATE CASCADE ON DELETE CASCADE;
GRANT DELETE, INSERT, REFERENCES(WORD_ID,FILE_ID), SELECT, UPDATE(WORD_ID,FILE_ID)
 ON FILE_SIG_WORDS TO  "DMSERVER";

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON FILE_SIG_WORDS TO  "SYSDBA" WITH GRANT OPTION;

ALTER TABLE FILTERS_DESCR ADD CONSTRAINT FK_UTENTI
  FOREIGN KEY ("USER") REFERENCES UTENTI (ID) ON UPDATE CASCADE ON DELETE CASCADE;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON FILTERS_DESCR TO  "DMSERVER";

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON FILTERS_DESCR TO  "SYSDBA" WITH GRANT OPTION;

ALTER TABLE FILTERS_WORDS ADD CONSTRAINT FK_FILTERS_WORDS_FILTERS_DESCR
  FOREIGN KEY (DESCR) REFERENCES FILTERS_DESCR (ID) ON UPDATE CASCADE ON DELETE CASCADE;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON FILTERS_WORDS TO  "DMSERVER";

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON FILTERS_WORDS TO  "SYSDBA" WITH GRANT OPTION;

ALTER TABLE GRP_CNCPT ADD CONSTRAINT FK_GRP_CNCPT_UTENTI
  FOREIGN KEY ("USER") REFERENCES UTENTI (ID) ON UPDATE CASCADE;
CREATE INDEX IGRP_CNCPTNEWINDEX ON GRP_CNCPT (ID);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON GRP_CNCPT TO  "DMSERVER";

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON GRP_CNCPT TO  "SYSDBA" WITH GRANT OPTION;

ALTER TABLE GRP_CNCPT_FILES ADD CONSTRAINT FK_GRP_CNCPT_FILES_FILEINFO
  FOREIGN KEY ("FILE") REFERENCES FILEINFO (ID) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE GRP_CNCPT_FILES ADD CONSTRAINT FK_GRP_CNCPT_FILES_GRP_CNCPT
  FOREIGN KEY (GRP_CNCPT) REFERENCES GRP_CNCPT (ID) ON UPDATE CASCADE ON DELETE CASCADE;
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON GRP_CNCPT_FILES TO  "DMSERVER";

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON GRP_CNCPT_FILES TO  "SYSDBA" WITH GRANT OPTION;

ALTER TABLE GRP_CNCPT_WORDS ADD CONSTRAINT GRP_CNCPT_ID
  FOREIGN KEY (GRP_CNCPT) REFERENCES GRP_CNCPT (ID) ON UPDATE CASCADE ON DELETE CASCADE;
CREATE INDEX IGRP_CNCPT_WORDSNEWINDEX ON GRP_CNCPT_WORDS (WORD,ID);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON GRP_CNCPT_WORDS TO  "DMSERVER";

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON GRP_CNCPT_WORDS TO  "SYSDBA" WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON LASTPATH TO  "DMSERVER";

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON LASTPATH TO  "SYSDBA" WITH GRANT OPTION;

UPDATE RDB$RELATION_FIELDS set RDB$DESCRIPTION = 'Il nome potrebbe trarre in inganno se non interpretato corretamente: il campo deve contenere le credenziali dell''utente ossia informazioni umanamente interpretabili per sapere quale sia la sua identita` reale (da questo la corretta interpretazione: identifier->identity) come, per esempio, nome e cognome.'  where RDB$FIELD_NAME = 'IDENTIFIER' and RDB$RELATION_NAME = 'UTENTI';
CREATE INDEX IUTENTINEWINDEX ON UTENTI (ID,USERNAME);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON UTENTI TO  "DMSERVER";

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON UTENTI TO  "SYSDBA" WITH GRANT OPTION;

